*** CODEFILE 4b ***

**** This file creates a geospatial database identifying the location of each Indian district
* It is used to create all spatial maps in the paper 

* Required: 
* ssc install geo2xy, replace
* ssc install palettes, replace
* ssc install colrspace, replace
* ssc install schemepack, replace
cd "Data/Spatial Data"
shp2dta using "districts", database(indb_dist.dta) coordinates(indcoord_dist.dta) genid(id) replace
use indb_dist, clear 
describe
* rename district names to match ASI dataset
{
	replace distname = "24-Parganas North" if distname == "South Twenty Four Parganas"
	replace distname = "24-Parganas South" if distname == "North Twenty Four Parganas"
	replace distname = "Ahmedabad" if distname == "Ahmadabad"
	replace distname = "Alappuzm" if distname == "Alappuzha"
	replace distname = "Anantpur" if distname == "Anantapur"
	replace distname = "Andaman" if distname == "North  & Middle Andaman"
	*replace distname = "Anugul" if distname == "Angul"
	replace distname = "Angul" if distname == "Anugul"
	replace distname = "Bagalkote" if distname == "Bagalkot"
	replace distname = "Bangalore (rural)" if distname == "Bangalore Rural"
	replace distname = "Bangalore (urban)" if distname == "Bangalore"
	replace distname = "Bans Kantha" if distname == "Banas Kantha"
	replace distname = "Baragarh" if distname == "Bargarh"
	replace distname = "Barmula" if distname == "Baramula"
	replace distname = "Bhabua" if distname == "Kaimur (Bhabua)"
	replace distname = "Bhilwani" if distname == "Bhiwani"
	replace distname = "Birdhum" if distname == "Birbhum"
	replace distname = "Calcutta" if distname == "Kolkata"
	replace distname = "Chamarajnagar" if distname == "Chamarajanagar"
	replace distname = "Chaundli" if distname == "Chandauli"
	replace distname = "Cuttak" if distname == "Cuttack"
	replace distname = "Dadar & Nagar Haveli" if distname == "Dadra & Nagar Haveli"
	replace distname = "Dakshin Kannad" if distname == "Dakshina Kannada"
	replace distname = "Darjeeling" if distname == "Darjiling"
	replace distname = "Dehradun (P)" if distname == "Dehradun"
	replace distname = "Dharampuri" if distname == "Dharmapuri"
	replace distname = "Dholpur" if distname == "Dhaulpur"
	replace distname = "Fatepur" if distname == "Fatehpur"
	replace distname = "G. Buddha Nagar" if distname == "Gautam Buddha Nagar"
	replace distname = "Giridihi" if distname == "Giridih"
	replace distname = "Hanuman Garh" if distname == "Hanumangarh"
	replace distname = "Hooghly" if distname == "Hugli"
	replace distname = "Greater Mumbai M.C. (urban)" if distname == "Mumbai"
	replace distname = "Greater Mumbai M.C. (urban)" if distname == "Mumbai Suburban"
	replace distname = "Hyderabad" if distname == "Hydrabad"
	replace distname = "Jagatsinghpura" if distname == "Jagatsinghapur"
	replace distname = "Jajpur" if distname == "Jajapur"
	replace distname = "Jhunjjuna" if distname == "Jhunjhunun"
	replace distname = "Kamrup Metropolitain" if distname == "Kamrup Metropolitan"
	replace distname = "Kanyakumari" if distname == "Kanniyakumari"
	replace distname = "Karbiaglong" if distname == "Karbi Anglong"
	replace distname = "Kasargod" if distname == "Kasaragod"
	replace distname = "Kathus" if distname == "Kathua"
	replace distname = "Khurda" if distname == "Khordha"
	replace distname = "Kochbihar" if distname == "Koch Bihar"
	replace distname = "Maharajganj" if distname == "Mahrajganj"
	replace distname = "Mahboob nagar" if distname == "Mahabubnagar"
	replace distname = "Malapuram" if distname == "Malappuram"
	replace distname = "Maldha" if distname == "Maldah"
	replace distname = "Nainital (P)" if distname == "Nainital"
	replace distname = "Navasari" if distname == "Navsari"
	replace distname = "Notrh Tripura" if distname == "North Tripura"
	replace distname = "Nuapara" if distname == "Nuapada"
	replace distname = "Palamau" if distname == "Palamu"
	replace distname = "Paschim Singhbhum" if distname == "Pashchimi Singhbhum"
	replace distname = "Pudukottai" if distname == "Pudukkottai"
	replace distname = "Purnea" if distname == "Purnia"
	replace distname = "Rai Bareli" if distname == "Rae Bareli"
	replace distname = "Ramnathapuram" if distname == "Ramanathapuram"
	replace distname = "Ranga reddy" if distname == "Rangareddy"
	replace distname = "Ri Bhoi" if distname == "Ribhoi"
	replace distname = "S. Kabir Nagar" if distname == "Sant Kabir Nagar"
	replace distname = "Sant Ravidas Nagar" if distname == "Sant Ravidas Nagar (Bhadohi)"
	replace distname = "Saraikela Khareswan" if distname == "Saraikela-Kharsawan"
	replace distname = "Sheikpura" if distname == "Sheikhpura"
	replace distname = "Sibsagar" if distname == "Sivasagar"
	replace distname = "Siramour" if distname == "Sirmaur"
	replace distname = "Sitamari" if distname == "Sitamarhi"
	replace distname = "Sivgangai" if distname == "Sivaganga"
	replace distname = "Sonbadra" if distname == "Sonbhadra"
	replace distname = "Thiruvannamalai" if distname == "Tiruvannamalai"
	replace distname = "Tiruchirapalli" if distname == "Tiruchirappalli"
	replace distname = "Tiruvallur" if distname == "Thiruvallur"
	replace distname = "Tiruvarur" if distname == "Thiruvarur"
	replace distname = "Trichur" if distname == "Thrissur"
	replace distname = "Triruvananthapuram" if distname == "Thiruvananthapuram"
	replace distname = "Uttar Kannad" if distname == "Uttara Kannada"
	replace distname = "Varanashi" if distname == "Varanasi"
	replace distname = "Villupuram" if distname == "Viluppuram"
	replace distname = "Virudhu Nagar" if distname == "Virudhunagar"
	replace distname = "Vishakhapatnam" if distname == "Visakhapatnam"
	replace distname = "Warangal" if distname == "Warangal (U)"
	replace distname = "Wayanand" if distname == "Wayanad"
	replace distname = "West Godawari" if distname == "West Godavari"
	replace distname = "Yamuna Nagar" if distname == "Yamunanagar"
	replace distname = "Bhatinda" if distname == "Bathinda"
	replace distname = "Bolangir" if distname == "Balangir"
	replace distname = "Boudh" if distname == "Baudh"
	replace distname = "Burdwan" if distname == "Barddhaman" // Not sure about this one
	replace distname = "Cuddapah" if distname == "Kadapa(YSR)"
	replace distname = "Deogarh" if distname == "Debagarh"
	replace distname = "East Champaran" if distname == "Purba Champaran"
	replace distname = "East Nimar" if distname == "Khandwa (East Nimar)"
	replace distname = "Goa North" if distname == "North Goa"
	replace distname = "Goa South" if distname == "South Goa"
	replace distname = "Hathras" if distname == "Mahamaya Nagar"
	replace distname = "Howrah" if distname == "Haora"
	replace distname = "Jaintia Hills" if distname == "West Jaintia Hills"
	replace distname = "Kahchipuram" if distname == "Kancheepuram"
	replace distname = "Kawardha" if distname == "Kabeerdham"
	replace distname = "Keonjhar" if distname == "Kendujhar"
	replace distname = "M.J.Phule Nagar" if distname == "Jyotiba Phule Nagar"
	replace distname = "Midnapur East" if distname == "Purba Medinipur"
	replace distname = "Midnapur West" if distname == "Paschim Medinipur"
	replace distname = "Mopong" if distname == "Mon"
	replace distname = "Mukokchung" if distname == "Mokokchung"
	replace distname = "Nawanshahr" if distname == "Shahid Bhagat Singh Nagar"
	replace distname = "Nellore" if distname == "Sri Potti Sriramulu Nellore"
	replace distname = "Nilgiri" if distname == "The Nilgiris"
	replace distname = "North Cachar Hills" if distname == "Dima Hasao"
	replace distname = "North Dinajpur" if distname == "Uttar Dinajpur"
	replace distname = "Nowarangpur" if distname == "Nabarangapur"
	replace distname = "Nowgong" if distname == "Nagaon"
	replace distname = "Phulbani" if distname == "Kandhamal"
	replace distname = "Sonepur" if distname == "Subarnapur"
	replace distname = "South Dinajpur" if distname == "Dakshin Dinajpur"
	replace distname = "Tuticorin" if distname == "Thoothukkudi"
	replace distname = "West Champaran" if distname == "Pashchim Champaran"
	replace distname = "West Nimar" if distname == "Khargone (West Nimar)"
	replace distname = "Dantewada" if distname == "Dakshin Bastar Dantewada"
	replace distname = "Kanker" if distname == "Uttar Bastar Kanker"
	replace distname = "Sidhartha nagar" if distname == "Siddharthnagar"
}
save indb_dist, replace
cd ../..